version: 2

build:
  image: latest

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
  system_packages:
    - python3.8-dev  # Replace with the correct package for your Python version
  before_script:
    - pip install -r requirements.txt
